# Generated by Django 4.2.20 on 2025-05-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='No message'),
        ),
    ]
