# Generated by Django 5.2 on 2025-05-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_0010_merge_20250429_1007_0012_alter_club_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='achievements',
        ),
    ]
