# Generated by Django 4.2.20 on 2025-05-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_notification_message_notification_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
